# Generated by Django 5.0.1 on 2024-07-03 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_wallet_razorpay_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet_razorpay_payment',
            name='status',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
