# Generated by Django 5.0.1 on 2024-07-03 02:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_wallet_razorpay_payment_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wallet_razorpay_payment',
            name='status',
        ),
    ]
