# Generated by Django 5.0.1 on 2024-02-03 19:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=150, unique=True)),
                ('soft_deleted', models.BooleanField(default=False)),
                ('category_details', models.TextField(blank=True, null=True)),
                ('is_available', models.BooleanField(blank=True, default=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=200, unique=True)),
                ('product_images', models.ImageField(upload_to='images/products')),
                ('description', models.TextField(blank=True, max_length=500)),
                ('price', models.IntegerField()),
                ('create_date', models.DateField(auto_now_add=True)),
                ('modified_date', models.DateField(auto_now=True)),
                ('available', models.BooleanField(default=True)),
                ('soft_deleted', models.BooleanField(default=False)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminmanager.category')),
            ],
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='photos/product')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='adminmanager.product')),
            ],
        ),
        migrations.CreateModel(
            name='Variant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ram', models.CharField(choices=[('4GB', '4GB'), ('8GB', '8GB'), ('16GB', '16GB')], max_length=50)),
                ('internal_memory', models.CharField(choices=[('64GB', '64GB'), ('128GB', '128GB'), ('256GB', '256GB')], max_length=50)),
                ('final_price', models.FloatField(blank=True, null=True)),
                ('is_available', models.BooleanField(default=True)),
                ('quantity', models.IntegerField(default=1000)),
                ('product', models.ManyToManyField(to='adminmanager.product')),
            ],
        ),
    ]
