# Generated by Django 5.0.1 on 2024-03-04 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminmanager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='variant',
            name='deleted',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
