# Generated by Django 5.0.1 on 2024-05-10 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminmanager', '0005_reviewrating_review_alter_reviewrating_comment_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reviewrating',
            old_name='varient',
            new_name='variant',
        ),
    ]
