# Generated by Django 5.0.1 on 2024-05-15 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminmanager', '0006_rename_varient_reviewrating_variant'),
    ]

    operations = [
        migrations.AddField(
            model_name='variant',
            name='low_stock_threshold',
            field=models.IntegerField(blank=True, default=50, null=True),
        ),
    ]
