# Generated by Django 5.0.1 on 2024-06-09 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminmanager', '0008_product_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='quantity',
        ),
    ]
