# Generated by Django 5.0.1 on 2024-06-10 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminmanager', '0010_prductoffers_product_offers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='offers',
        ),
        migrations.DeleteModel(
            name='PrductOffers',
        ),
    ]
