# Generated by Django 5.0.1 on 2024-06-12 01:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminmanager', '0011_remove_product_offers_delete_prductoffers'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductOffers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_offer', models.CharField(max_length=100)),
                ('discount', models.IntegerField(default=0)),
                ('valid_from', models.DateTimeField()),
                ('valid_to', models.DateTimeField()),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='product_offer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='adminmanager.productoffers'),
        ),
    ]
