# Generated by Django 5.0.1 on 2024-06-14 07:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminmanager', '0014_remove_variant_product_variant_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryOffers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_offer', models.CharField(max_length=100)),
                ('discount', models.IntegerField(default=0)),
                ('valid_from', models.DateTimeField()),
                ('valid_to', models.DateTimeField()),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name='category',
            name='category_offer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='adminmanager.categoryoffers'),
        ),
    ]
