# Generated by Django 5.0.1 on 2024-02-14 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='land_mark',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
