# Generated by Django 5.0.1 on 2024-02-16 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0003_coupons_usercoupons'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='usercoupons',
            unique_together=set(),
        ),
    ]
