# Generated by Django 5.0.1 on 2024-03-04 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0004_alter_usercoupons_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercoupons',
            name='is_used',
            field=models.BooleanField(),
        ),
    ]
