# Generated by Django 5.0.1 on 2024-03-08 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0005_alter_usercoupons_is_used'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercoupons',
            name='is_used',
            field=models.BooleanField(default=False),
        ),
    ]
