# Generated by Django 5.0.1 on 2024-06-09 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0008_alter_address_options_wishlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupons',
            name='max_usage_count',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='coupons',
            name='usage_count',
            field=models.IntegerField(default=0),
        ),
    ]
