# Generated by Django 5.0.1 on 2024-06-09 21:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0009_coupons_max_usage_count_coupons_usage_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coupons',
            name='max_usage_count',
        ),
        migrations.RemoveField(
            model_name='coupons',
            name='usage_count',
        ),
    ]
