# Generated by Django 5.0.1 on 2024-02-03 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='added_quantity',
            field=models.IntegerField(default=1),
        ),
    ]
