# Generated by Django 5.0.1 on 2024-03-08 20:31

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartapp', '0002_alter_cartitem_added_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='date_added',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
