# Generated by Django 5.0.1 on 2024-03-08 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartapp', '0003_alter_cartitem_date_added'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='date_added',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='date_added',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
