# Generated by Django 5.0.1 on 2024-06-27 02:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('adminmanager', '0015_categoryoffers_category_category_offer'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(default='88E4C263', max_length=8, unique=True)),
                ('delivery_address', models.JSONField()),
                ('order_total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('payment_method', models.CharField(blank=True, choices=[('Razorpay', 'Razorpay'), ('COD', 'COD'), ('wallet', 'wallet')], max_length=30, null=True)),
                ('coupon_discount', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('offer_discount', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('shipping', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('tax', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('grand_total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('order_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Ordered', 'Ordered'), ('OrderPending', 'Orderpending'), ('orderfailed', 'orderfailed'), ('Packed', 'Packed'), ('Shipped', 'Shipped'), ('Delivered', 'Delivered'), ('Cancelled', 'Cancelled'), ('Returned', 'Returned')], default='Orderpending', max_length=20, null=True)),
                ('is_active', models.BooleanField(default=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('memmory', models.CharField(max_length=10)),
                ('ram', models.CharField(max_length=20)),
                ('quantity', models.IntegerField(default=1)),
                ('offer_price', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('product_discount', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('category_discount', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminmanager.product')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminmanager.variant')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.orders')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_id', models.CharField(blank=True, max_length=100, null=True)),
                ('payment_method', models.CharField(max_length=100)),
                ('amount_paid', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.orders')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'payment',
                'verbose_name_plural': ' payments',
            },
        ),
        migrations.CreateModel(
            name='Razorpay_payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razorpay_payment_id', models.CharField(max_length=30, unique=True)),
                ('amount', models.IntegerField(blank=True, null=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.orders')),
            ],
        ),
    ]
