# Generated by Django 5.0.1 on 2024-03-06 14:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0005_alter_usercoupons_is_used'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='order_id',
            field=models.CharField(default='F1D6D205', max_length=8, unique=True),
        ),
        migrations.AlterField(
            model_name='orders',
            name='delivery_address',
            field=models.ForeignKey(limit_choices_to={'is_primary': True, 'user': models.F('user')}, on_delete=django.db.models.deletion.CASCADE, to='authapp.address'),
        ),
    ]
