# Generated by Django 5.0.1 on 2024-06-27 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='order_id',
            field=models.CharField(default='04389479', max_length=8, unique=True),
        ),
    ]
