# Generated by Django 5.0.1 on 2024-06-27 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_orders_order_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='order_id',
            field=models.CharField(default='53258E29', max_length=8, unique=True),
        ),
    ]
