# Generated by Django 5.0.1 on 2024-03-08 10:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartapp', '0002_alter_cartitem_added_quantity'),
        ('orders', '0002_orders_order_id_alter_orders_delivery_address'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='variantn',
            new_name='variant',
        ),
        migrations.AlterField(
            model_name='orders',
            name='cart',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cartapp.cart'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='order_id',
            field=models.CharField(default='53C5E61A', max_length=8, unique=True),
        ),
    ]
