# Generated by Django 5.0.1 on 2024-07-03 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_alter_orders_order_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='order_id',
            field=models.CharField(default='E70CE974', max_length=8, unique=True),
        ),
    ]
