# Generated by Django 5.0.1 on 2024-03-08 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_alter_orders_order_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='cart',
        ),
        migrations.AlterField(
            model_name='orders',
            name='order_id',
            field=models.CharField(default='076CF187', max_length=8, unique=True),
        ),
    ]
