# Generated by Django 5.0.1 on 2024-07-03 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_alter_orders_order_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='order_id',
            field=models.CharField(default='02FEE56C', max_length=8, unique=True),
        ),
    ]
