# Generated by Django 5.0.1 on 2024-05-09 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_alter_orders_order_id_razorpay_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='razorpay_payment',
            name='amount',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='orders',
            name='order_id',
            field=models.CharField(default='A8579D0E', max_length=8, unique=True),
        ),
    ]
