# Generated by Django 5.0.1 on 2024-05-09 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_razorpay_payment_amount_alter_orders_order_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='order_id',
            field=models.CharField(default='56D5C7C8', max_length=8, unique=True),
        ),
    ]
