# Generated by Django 5.0.1 on 2024-05-15 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0016_alter_orders_order_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='order_id',
            field=models.CharField(default='AFB7BBE7', max_length=8, unique=True),
        ),
    ]
