# Generated by Django 5.0.1 on 2024-05-29 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0019_alter_orders_order_id_alter_orders_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='order_id',
            field=models.CharField(default='19D0B3E4', max_length=8, unique=True),
        ),
    ]
