# Generated by Django 5.0.1 on 2024-06-09 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0021_alter_orders_order_id_alter_orders_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='delivery_address',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='orders',
            name='order_id',
            field=models.CharField(default='B1382ADA', max_length=8, unique=True),
        ),
    ]
