# Generated by Django 5.0.1 on 2024-06-09 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0022_alter_orders_delivery_address_alter_orders_order_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='order_id',
            field=models.CharField(default='67CBE51B', max_length=8, unique=True),
        ),
    ]
