# Generated by Django 5.0.1 on 2024-06-09 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0024_alter_orders_order_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='order_id',
            field=models.CharField(default='B07D10CE', max_length=8, unique=True),
        ),
    ]
