# Generated by Django 5.0.1 on 2024-06-12 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0028_alter_orders_order_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='order_id',
            field=models.CharField(default='E225A5C9', max_length=8, unique=True),
        ),
    ]
