# Generated by Django 5.0.1 on 2024-06-14 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0032_alter_orders_order_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orders',
            old_name='discount_given',
            new_name='category_discount',
        ),
        migrations.AddField(
            model_name='orders',
            name='coupon_discount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name='orders',
            name='product_discount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='orders',
            name='order_id',
            field=models.CharField(default='34ACFA77', max_length=8, unique=True),
        ),
        migrations.AlterField(
            model_name='orders',
            name='shipping',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='orders',
            name='tax',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
    ]
