# Generated by Django 5.0.1 on 2024-06-14 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0033_rename_discount_given_orders_category_discount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='category_discount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='product_discount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='orders',
            name='order_id',
            field=models.CharField(default='AAB5AF08', max_length=8, unique=True),
        ),
    ]
