# Generated by Django 5.0.1 on 2024-06-15 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0036_remove_orders_category_discount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='order_id',
            field=models.CharField(default='F50E009E', max_length=8, unique=True),
        ),
    ]
