# Generated by Django 5.0.1 on 2024-06-15 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0038_orders_offer_discount_alter_orders_order_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='order_id',
            field=models.CharField(default='C3444DAA', max_length=8, unique=True),
        ),
    ]
