# Generated by Django 5.0.1 on 2024-06-16 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0039_alter_orders_order_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='offer_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='orders',
            name='order_id',
            field=models.CharField(default='F0D91FBD', max_length=8, unique=True),
        ),
    ]
